blank_issues_enabled: false
contact_links:
  - name: üí¨ Telegram Support
    url: https://t.me/PandaPalBot
    about: –ü–æ–ª—É—á–∏ –ø–æ–º–æ—â—å —á–µ—Ä–µ–∑ Telegram –±–æ—Ç–∞
  - name: üìö Documentation
    url: https://github.com/gaus-1/pandapal-bot/tree/main/docs
    about: –ü–æ—Å–º–æ—Ç—Ä–∏ –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—é –ø—Ä–æ–µ–∫—Ç–∞
